import type { FieldDef, FormSchema, SectionDef, FieldOption } from './schema-types';

// Schema seeded from Fiche MO TAK(1) VU.xlsm — 391 fields + 10 debit-de-dose extras = 401 fields total.
// Edit via the in-app schema editor (/app/schema).

const opt = (...values: string[]): FieldOption[] => values.map((v) => ({ value: v }));

const SECTIONS: SectionDef[] = [
  { id: 'identification', label: 'Identification', order: 1 },
  { id: 'atcd', label: 'Antécédents', order: 2 },
  { id: 'diagnostic_cdt', label: 'Diagnostic CDT', order: 3 },
  { id: 'metastases', label: 'Métastases (M1)', order: 4 },
  { id: 'bilan_extension', label: 'Bilan d\'extension', order: 5 },
  { id: 'preparation_i1', label: 'Préparation initiale (état, douleur, bilans)', order: 6 },
  { id: 'i1_avant_2021', label: 'I1 avant 2021 (synthèse historique)', order: 7 },
  { id: 'cure_i1', label: 'Cure I1', order: 8 },
  { id: 'cure_i2', label: 'Cure I2', order: 9 },
  { id: 'cure_i3', label: 'Cure I3', order: 10 },
  { id: 'cure_i4', label: 'Cure I4', order: 11 },
  { id: 'cure_i5_i6', label: 'Cures I5 / I6', order: 12 },
  { id: 'suivi_devenir', label: 'Suivi global et devenir', order: 13 },
];

const FIELDS: FieldDef[] = [
  { id: 'numero', label: 'Numéro', sectionId: 'identification', type: 'text', order: 1, required: true },
  { id: 'nom', label: 'Nom', sectionId: 'identification', type: 'text', order: 2, required: true },
  { id: 'prenoms', label: 'Prénoms', sectionId: 'identification', type: 'text', order: 3, required: true },
  { id: 'sexe', label: 'Sexe', sectionId: 'identification', type: 'enum', order: 4, options: opt('H', 'F'), required: true },
  { id: 'ddn', label: 'DDN', sectionId: 'identification', type: 'date', order: 5 },
  { id: 'age_a_l_ouverture', label: 'Âge à l\'ouverture', sectionId: 'identification', type: 'number', order: 6 },
  { id: 'telephone_1', label: 'Téléphone 1', sectionId: 'identification', type: 'phone', order: 7 },
  { id: 'telephone_2', label: 'Télephone 2', sectionId: 'identification', type: 'number', order: 8 },
  { id: 'origine', label: 'Origine', sectionId: 'identification', type: 'enum', order: 9, options: opt('Adrar', 'Aïn Defla', 'Aïn Témouchent', 'Alger', 'Annaba', 'Batna', 'Béchar', 'Béjaïa', 'Béni Abbès', 'Biskra', 'Blida', 'Bordj Badji Mokhtar', 'Bordj Bou Arréridj', 'Bouira', 'Boumerdès', 'Chlef', 'Constantine', 'Djanet', 'Djelfa', 'El Bayadh', 'El M\'Ghair', 'El Meniaa', 'El Oued', 'El Tarf', 'Ghardaïa', 'Guelma', 'Illizi', 'In Guezzam', 'In Salah', 'Jijel', 'Khenchela', 'Laghouat', 'M\'Sila', 'Mascara', 'Médéa', 'Mila', 'Mostaganem', 'Naâma', 'Oran', 'Ouargla', 'Ouled Djellal', 'Oum El Bouaghi', 'Relizane', 'Saïda', 'Sétif', 'Sidi Bel Abbès', 'Skikda', 'Souk Ahras', 'Tamanrasset', 'Tébessa', 'Tiaret', 'Timimoun', 'Tindouf', 'Tipaza', 'Tissemsilt', 'Tizi Ouzou', 'Tlemcen', 'Touggourt') },
  { id: 'adresse', label: 'Adresse', sectionId: 'identification', type: 'enum', order: 10, options: opt('Adrar', 'Aïn Defla', 'Aïn Témouchent', 'Alger', 'Annaba', 'Batna', 'Béchar', 'Béjaïa', 'Béni Abbès', 'Biskra', 'Blida', 'Bordj Badji Mokhtar', 'Bordj Bou Arréridj', 'Bouira', 'Boumerdès', 'Chlef', 'Constantine', 'Djanet', 'Djelfa', 'El Bayadh', 'El M\'Ghair', 'El Meniaa', 'El Oued', 'El Tarf', 'Ghardaïa', 'Guelma', 'Illizi', 'In Guezzam', 'In Salah', 'Jijel', 'Khenchela', 'Laghouat', 'M\'Sila', 'Mascara', 'Médéa', 'Mila', 'Mostaganem', 'Naâma', 'Oran', 'Ouargla', 'Ouled Djellal', 'Oum El Bouaghi', 'Relizane', 'Saïda', 'Sétif', 'Sidi Bel Abbès', 'Skikda', 'Souk Ahras', 'Tamanrasset', 'Tébessa', 'Tiaret', 'Timimoun', 'Tindouf', 'Tipaza', 'Tissemsilt', 'Tizi Ouzou', 'Tlemcen', 'Touggourt') },
  { id: 'situation_familiale', label: 'Situation familiale', sectionId: 'identification', type: 'enum', order: 11, options: opt('Marié(e)', 'Célibataire', 'Divorcé(e)', 'Veuf(ve)', 'Non précisé') },
  { id: 'atcd_gynecologiques', label: 'ATCD Gynécologiques', sectionId: 'atcd', type: 'multi', order: 1, options: opt('Sans ATCD', 'Normoréglée', 'Aménorrhée', 'Ménopausée', 'Hystérectomisée', 'Ligature de trompes', 'Non précisé') },
  { id: 'atcd_personnels_non_neoplasiques', label: 'ATCD Personnels non néoplasiques', sectionId: 'atcd', type: 'multi', order: 2, options: opt('Sans ATCD', 'HTA', 'Diabète', 'Allergie', 'Asthme bronchique', 'Cardiopathie', 'Neuropathie', 'Autres', 'Non précisé') },
  { id: 'atcd_personnels_neoplasiques', label: 'ATCD Personnels néoplasiques', sectionId: 'atcd', type: 'multi', order: 3, options: opt('Sans ATCD', 'Néoplasie du sein', 'Néoplasie du côlon', 'Néoplasie du poumon', 'Néoplasie gynécologique', 'Lymphome', 'Néoplasie de la prostate', 'Néoplasie de l\'estomac', 'Autres', 'Non précisé') },
  { id: 'atcd_familiaux_endocriniens', label: 'ATCD Familiaux Endocriniens', sectionId: 'atcd', type: 'multi', order: 4, options: opt('Sans ATCD', 'Diabète', 'Pathologie thyroïdienne', 'Autres endocrinopathies', 'Non précisé') },
  { id: 'atcd_familiaux_cdt', label: 'ATCD Familiaux CDT', sectionId: 'atcd', type: 'enum', order: 5, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_combien_de_cdt_dans_la_famille', label: 'Si Oui : combien de CDT dans la famille', sectionId: 'atcd', type: 'number', order: 6 },
  { id: 'circonstances_de_decouverte_du_cdt', label: 'Circonstances de Découverte du CDT', sectionId: 'diagnostic_cdt', type: 'multi', order: 1, options: opt('Nodule thyroïdien', 'GMN', 'Adénopathie', 'Dysthyroïdie', 'Fortuite', 'Métastase révélatrice', 'Bilan d\'extension', 'Non précisées') },
  { id: 'date_de_dgc_cdt', label: 'Date de Dgc CDT', sectionId: 'diagnostic_cdt', type: 'date', order: 2 },
  { id: 'specialite_chirurgicale', label: 'Spécialité Chirurgicale', sectionId: 'diagnostic_cdt', type: 'enum', order: 3, options: opt('Chirurgie générale', 'ORL', 'Chirurgie thoracique', 'Autres') },
  { id: 'lieu_de_la_chirurgie', label: 'Lieu de la Chirurgie', sectionId: 'diagnostic_cdt', type: 'enum', order: 4, options: opt('Secteur privé', 'CHU', 'EHS', 'EPH', 'EPSP') },
  { id: 'type_de_chirurgie', label: 'Type de Chirurgie', sectionId: 'diagnostic_cdt', type: 'enum', order: 5, options: opt('Thyroïdectomie totale en un seul temps', 'Thyroïdectomie totale en deux temps', 'Thyroïdectomie subtotale', 'Thyroïdectomie partielle', 'Totalisation (après ancienne chirurgie)') },
  { id: 'curage_ganglionnaire', label: 'Curage Ganglionnaire', sectionId: 'diagnostic_cdt', type: 'enum', order: 6, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_en_quel_temps', label: 'Si Oui en Quel Temps', sectionId: 'diagnostic_cdt', type: 'enum', order: 7, options: opt('en un seul temps', 'au premier temps', 'au deuxième temps', 'aux deux temps') },
  { id: 'si_oui_type', label: 'Si Oui Type', sectionId: 'diagnostic_cdt', type: 'multi', order: 8, options: opt('Central', 'Latéral unilatéral', 'Latéral bilatéral', 'Central et latéral unilatéral', 'Central et latéral bilatéral') },
  { id: 'type_histologique', label: 'Type Histologique', sectionId: 'diagnostic_cdt', type: 'enum', order: 9, options: opt('Papillaire', 'Vésiculaire', 'Oncocytaire', 'Peu différencié', 'NIFTP', 'Non documenté') },
  { id: 'variante', label: 'Variante', sectionId: 'diagnostic_cdt', type: 'enum', order: 10, options: opt('Classique', 'Vésiculaire', 'à cellules hautes', 'à cellules cylindriques', 'Sclérosant diffus', 'Oncocytaire', 'Cribriforme', 'Hobnail (Clou de tapissier)', 'Warthin Like', 'à invasion minime', 'Macro-invasif', 'à cellules claires', 'Pur', 'Insulaire', 'Trabéculaire', 'Solide', 'Trabéculo-solide', 'Autres') },
  { id: 'taille_t_plus_gd_en_cm', label: 'Taille T (plus Gd) en cm', sectionId: 'diagnostic_cdt', type: 'number', order: 11 },
  { id: 'nombre_t', label: 'Nombre T', sectionId: 'diagnostic_cdt', type: 'number', order: 12 },
  { id: 'atteinte_lobaire', label: 'Atteinte Lobaire', sectionId: 'diagnostic_cdt', type: 'enum', order: 13, options: opt('Unilatéral', 'Bilatéral', 'Isthmique', 'Lobo-isthmique', 'Non précisée') },
  { id: 'effraction_capsulaire', label: 'Effraction Capsulaire', sectionId: 'diagnostic_cdt', type: 'enum', order: 14, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'atteinte_des_tissus_avoisinants', label: 'Atteinte des tissus avoisinants', sectionId: 'diagnostic_cdt', type: 'enum', order: 15, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'emboles_vasculaires', label: 'Emboles Vasculaires', sectionId: 'diagnostic_cdt', type: 'enum', order: 16, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_nombre', label: 'Si Oui : Nombre', sectionId: 'diagnostic_cdt', type: 'number', order: 17 },
  { id: 'nombre_de_ganglions_reseques', label: 'Nombre de Ganglions réséqués', sectionId: 'diagnostic_cdt', type: 'number', order: 18 },
  { id: 'nombre_de_ganglions_atteints', label: 'Nombre de Ganglions atteints', sectionId: 'diagnostic_cdt', type: 'number', order: 19 },
  { id: 'ihc', label: 'IHC', sectionId: 'diagnostic_cdt', type: 'enum', order: 20, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'tnm_2009_ou_2017', label: 'TNM 2009 ou 2017', sectionId: 'diagnostic_cdt', type: 'enum', order: 21, options: opt('2009', '2017') },
  { id: 'tnm_initial_t', label: 'TNM initial (T)', sectionId: 'diagnostic_cdt', type: 'enum', order: 22, options: opt('Tx', 'T0', 'T1', 'T1a', 'T1b', 'T2', 'T3', 'T3a', 'T3b', 'T4', 'T4a', 'T4b') },
  { id: 'tnm_initial_n', label: 'TNM initial (N)', sectionId: 'diagnostic_cdt', type: 'enum', order: 23, options: opt('Nx', 'N0', 'N1a', 'N1b') },
  { id: 'tnm_initial_m', label: 'TNM initial (M)', sectionId: 'diagnostic_cdt', type: 'enum', order: 24, options: opt('Mx', 'M0', 'M1') },
  { id: 'ajcc_2010_ou_2018', label: 'AJCC 2010 ou 2018', sectionId: 'diagnostic_cdt', type: 'enum', order: 25, options: opt('2010', '2018') },
  { id: 'ajcc_initial', label: 'AJCC initial', sectionId: 'diagnostic_cdt', type: 'enum', order: 26, options: opt('I', 'II', 'III', 'IVA', 'IVB', 'IVC') },
  { id: 'circonstances_de_decouverte_de_m1', label: 'Circonstances de Découverte de M1', sectionId: 'metastases', type: 'multi', order: 1, options: opt('Pas de métastases connues avant I1', 'Dyspnée', 'Hémoptysie', 'Dysphagie', 'Tuméfaction osseuse', 'Douleurs osseuses', 'Fracture', 'Compression médullaire', 'Hypercalcémie', 'Fortuite', 'Bilan d\'extension', 'Non précisées') },
  { id: 'date_de_dgc_m1', label: 'Date de Dgc M1', sectionId: 'metastases', type: 'date', order: 2 },
  { id: 's_agit_il_de_m1_osseuse', label: 's\'agit il de M1 osseuse', sectionId: 'metastases', type: 'enum', order: 3, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_nombre_2', label: 'Si Oui : Nombre', sectionId: 'metastases', type: 'number', order: 4 },
  { id: 'rachis', label: 'Rachis', sectionId: 'metastases', type: 'enum', order: 5, options: opt('Oui', 'Non') },
  { id: 'pelvis', label: 'Pelvis', sectionId: 'metastases', type: 'enum', order: 6, options: opt('Oui', 'Non') },
  { id: 'thorax', label: 'Thorax', sectionId: 'metastases', type: 'enum', order: 7, options: opt('Oui', 'Non') },
  { id: 'crane', label: 'Crâne', sectionId: 'metastases', type: 'enum', order: 8, options: opt('Oui', 'Non') },
  { id: 'membres', label: 'Membres', sectionId: 'metastases', type: 'enum', order: 9, options: opt('Oui', 'Non') },
  { id: 'biopsie_osseuse', label: 'Biopsie Osseuse', sectionId: 'metastases', type: 'enum', order: 10, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'chirurgie_osseuse', label: 'Chirurgie Osseuse', sectionId: 'metastases', type: 'enum', order: 11, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_siege', label: 'Si Oui Siège', sectionId: 'metastases', type: 'multi', order: 12, options: opt('Rachis', 'Pelvis', 'Thorax', 'Crâne', 'Membres') },
  { id: 'type_de_chirurgie_de_la_mo', label: 'Type de Chirurgie de la MO', sectionId: 'metastases', type: 'enum', order: 13, options: opt('Ablative', 'Stabilisatrice / Réparatrice', 'Palliative') },
  { id: 'geste_operatoire', label: 'Geste Opératoire', sectionId: 'metastases', type: 'multi', order: 14, options: opt('Résection complète', 'Exérèse', 'Hémivertèbrectomie / Vertèbrectomie', 'Amputation', 'Ostéosynthèse', 'Arthroplastie', 'Cimentoplastie', 'Greffe osseuse', 'Décompression médullaire / Laminectomie', 'Fixateur interne') },
  { id: 'preuve_hisotologique', label: 'Preuve Hisotologique', sectionId: 'metastases', type: 'text', order: 15 },
  { id: 'ihc_2', label: 'IHC', sectionId: 'metastases', type: 'enum', order: 16, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'autres_metastases', label: 'Autres Métastases', sectionId: 'metastases', type: 'multi', order: 17, options: opt('Non documenté', 'Non', 'Ganglionnaires', 'Pulmonaires', 'Cérébrales', 'Hépatiques', 'Cutanéo-musculaires', 'Autres') },
  { id: 'autres_traitements', label: 'Autres Traitements', sectionId: 'metastases', type: 'multi', order: 18 },
  { id: 'age_du_dgc_cdt', label: 'Âge du Dgc  CDT', sectionId: 'metastases', type: 'number', order: 19 },
  { id: 'age_du_dgc_m1', label: 'Âge du Dgc M1', sectionId: 'metastases', type: 'number', order: 20 },
  { id: 'delai_dg_m1_dgc_t_mois', label: 'Délai Dg M1/Dgc T (mois)', sectionId: 'metastases', type: 'number', order: 21 },
  { id: 'echographie_cervicale', label: 'Echographie Cervicale', sectionId: 'bilan_extension', type: 'enum', order: 1, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'loge_thyroidienne', label: 'Loge Thyroïdienne', sectionId: 'bilan_extension', type: 'text', order: 2 },
  { id: 'classification_eu_tirads', label: 'Classification EU-Tirads', sectionId: 'bilan_extension', type: 'enum', order: 3, options: opt('1', '2', '3', '4', '5') },
  { id: 'aires_ganglionnaires', label: 'Aires Ganglionnaires', sectionId: 'bilan_extension', type: 'text', order: 4 },
  { id: 'aspect_des_ganglions', label: 'Aspect des Ganglions', sectionId: 'bilan_extension', type: 'text', order: 5 },
  { id: 'cytologie_thyroidienne', label: 'Cytologie Thyroïdienne', sectionId: 'bilan_extension', type: 'enum', order: 6, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'classification_bethesda', label: 'Classification Bethesda', sectionId: 'bilan_extension', type: 'enum', order: 7, options: opt('I', 'II', 'III', 'IV', 'V', 'VI') },
  { id: 'tg_intra_ganglionnaire', label: 'Tg Intra-Ganglionnaire', sectionId: 'bilan_extension', type: 'enum', order: 8, options: opt('Oui', 'Non', 'Non précisée') },
  { id: 'resultat_de_la_tg_in_situ', label: 'Résultat de la Tg in situ', sectionId: 'bilan_extension', type: 'text', order: 9 },
  { id: 'tdm_thoracique_tap', label: 'TDM Thoracique/TAP', sectionId: 'bilan_extension', type: 'enum', order: 10, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_tdm', label: 'Résultats TDM', sectionId: 'bilan_extension', type: 'multi', order: 11 },
  { id: 'irm_cerebro_medullaire', label: 'IRM Cérébro-Médullaire', sectionId: 'bilan_extension', type: 'enum', order: 12, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_irm', label: 'Résultats IRM', sectionId: 'bilan_extension', type: 'multi', order: 13 },
  { id: 'scintigraphie_osseuse', label: 'Scintigraphie Osseuse', sectionId: 'bilan_extension', type: 'enum', order: 14, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_so', label: 'Résultats SO', sectionId: 'bilan_extension', type: 'number', order: 15 },
  { id: 'tep_fdg', label: 'TEP FDG', sectionId: 'bilan_extension', type: 'enum', order: 16, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_fdg', label: 'Résultats FDG', sectionId: 'bilan_extension', type: 'multi', order: 17 },
  { id: 'autres_examens', label: 'Autres Examens', sectionId: 'bilan_extension', type: 'text', order: 18 },
  { id: 'sous_biphosphonate', label: 'Sous Biphosphonate', sectionId: 'bilan_extension', type: 'enum', order: 19, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'sous_l_thyroxine', label: 'Sous L-Thyroxine', sectionId: 'bilan_extension', type: 'enum', order: 20, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'bilan_thyroidien_externe', label: 'Bilan Thyroïdien (Externe)', sectionId: 'bilan_extension', type: 'text', order: 21 },
  { id: 'tshus_ui_ml', label: 'TSHus µUI/ml', sectionId: 'bilan_extension', type: 'number', order: 22 },
  { id: 'ft4_pmol_l', label: 'FT4 pmol/l', sectionId: 'bilan_extension', type: 'number', order: 23 },
  { id: 'tg_ng_ml_sans_dilution', label: 'Tg ng/ml (sans dilution)', sectionId: 'bilan_extension', type: 'number', order: 24 },
  { id: 'tg_ng_ml_exact', label: 'Tg ng/ml (Exact)', sectionId: 'bilan_extension', type: 'number', order: 25 },
  { id: 'ac_anti_tg_ui_ml', label: 'Ac Anti-Tg UI/ml', sectionId: 'bilan_extension', type: 'number', order: 26 },
  { id: 'titre_des_anti_tg_si_faite', label: 'Titre des Anti-Tg (si faite)', sectionId: 'bilan_extension', type: 'number', order: 27 },
  { id: 'tct_pg_ml', label: 'TCT pg/ml', sectionId: 'bilan_extension', type: 'number', order: 28 },
  { id: 'cdt_ira', label: 'CDT IRA', sectionId: 'preparation_i1', type: 'text', order: 1 },
  { id: 'date_a_l_ouverture_du_dossier', label: 'Date à l\'Ouverture du dossier', sectionId: 'preparation_i1', type: 'date', order: 2 },
  { id: 'etat_general', label: 'Etat Général', sectionId: 'preparation_i1', type: 'text', order: 3 },
  { id: 'autonomie', label: 'Autonomie', sectionId: 'preparation_i1', type: 'enum', order: 4, options: opt('Oui', 'Non') },
  { id: 'deambulation', label: 'Déambulation', sectionId: 'preparation_i1', type: 'enum', order: 5, options: opt('Conservée', 'Ralentie', 'avec canne', 'avec béquilles', 'sur fauteuil roulant', 'Patient(e) alité(e)') },
  { id: 'score_de_karnofsky', label: 'Score de Karnofsky', sectionId: 'preparation_i1', type: 'enum', order: 6, options: opt('100-90', '80-70', '60-50', '40-30', '≤ 20') },
  { id: 'douleur', label: 'Douleur', sectionId: 'preparation_i1', type: 'enum', order: 7, options: opt('Oui', 'Non') },
  { id: 'nombre_de_sites', label: 'Nombre de Sites', sectionId: 'preparation_i1', type: 'number', order: 8 },
  { id: 'intensite', label: 'Intensité', sectionId: 'preparation_i1', type: 'enum', order: 9, options: opt('Absence', 'Légère', 'Modérée', 'Sévère') },
  { id: 'eva', label: 'EVA', sectionId: 'preparation_i1', type: 'number', order: 10 },
  { id: 'impotence_fonctionnelle', label: 'Impotence Fonctionnelle', sectionId: 'preparation_i1', type: 'enum', order: 11, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'trouble_neurologique', label: 'Trouble Neurologique', sectionId: 'preparation_i1', type: 'multi', order: 12, options: opt('Absent', 'Paresthésie-Hypoesthésie', 'Douleur radiculaire', 'Faiblesse musculaire', 'Parésie-Paralysie', 'Amyotrophie', 'Incontinence urinaire') },
  { id: 'sous_l_thyroxine_2', label: 'sous L-Thyroxine', sectionId: 'preparation_i1', type: 'enum', order: 13, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'degres_de_freinage', label: 'Degrès de Freinage', sectionId: 'preparation_i1', type: 'enum', order: 14, options: opt('Bien freiné', 'Mal freiné', 'en hypothyroïdie', 'Non précisé') },
  { id: 'bilan_thyroidien_ria', label: 'Bilan Thyroïdien (RIA)', sectionId: 'preparation_i1', type: 'text', order: 15 },
  { id: 'tshus_ui_ml_2', label: 'TSHus µUI/ml', sectionId: 'preparation_i1', type: 'number', order: 16 },
  { id: 'tg_ng_ml_sans_dilution_2', label: 'Tg ng/ml (sans dilution)', sectionId: 'preparation_i1', type: 'number', order: 17 },
  { id: 'tg_ng_ml_exact_2', label: 'Tg ng/ml (Exact)', sectionId: 'preparation_i1', type: 'number', order: 18 },
  { id: 'ac_anti_tg_ui_ml_2', label: 'Ac Anti-Tg UI/ml', sectionId: 'preparation_i1', type: 'number', order: 19 },
  { id: 'titre_des_anti_tg_si_faite_2', label: 'Titre des Anti-Tg (si faite)', sectionId: 'preparation_i1', type: 'number', order: 20 },
  { id: 'ec_pre_i1', label: 'EC pré I1', sectionId: 'preparation_i1', type: 'multi', order: 21, options: opt('Non faite', 'RAS', 'Reliquat thyroïdien', 'Nodule thyroïdien', 'Lobe restant', 'Adénopathies', 'Extension extra-thyroïdienne') },
  { id: 'so_demandee_en_mn', label: 'SO demandée en MN', sectionId: 'preparation_i1', type: 'enum', order: 22, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'resultats_so_2', label: 'Résultats SO', sectionId: 'preparation_i1', type: 'text', order: 23 },
  { id: 'demande_d_avis_chirurgical', label: 'Demande d\'Avis chirurgical', sectionId: 'preparation_i1', type: 'enum', order: 24, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_reponse', label: 'Si Oui : Réponse', sectionId: 'preparation_i1', type: 'text', order: 25 },
  { id: 'reprise_chirurgicale', label: 'Reprise Chirurgicale', sectionId: 'preparation_i1', type: 'enum', order: 26, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_resultats', label: 'Si Oui : Résultats', sectionId: 'preparation_i1', type: 'text', order: 27 },
  { id: 'demande_de_rte', label: 'Demande de RTE', sectionId: 'preparation_i1', type: 'enum', order: 28, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_reponse_2', label: 'Si Oui : Réponse', sectionId: 'preparation_i1', type: 'text', order: 29 },
  { id: 'changment_du_statut_m1_avant_i1', label: 'Changment du statut M1 avant I1', sectionId: 'preparation_i1', type: 'text', order: 30 },
  { id: 'delai_entre_chirurgie_thyroidienne_et_i1_mois', label: 'Délai entre Chirurgie Thyroïdienne et I1 (mois)', sectionId: 'preparation_i1', type: 'number', order: 31 },
  { id: 'i1_avant_2021', label: 'I1 avant 2021', sectionId: 'i1_avant_2021', type: 'enum', order: 1, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'si_oui_nombre_de_cures_jusqu_a_2020', label: 'Si Oui : Nombre de Cures jusqu\'à 2020', sectionId: 'i1_avant_2021', type: 'number', order: 2 },
  { id: 'activite_cumulee_en_mci_jusqu_a_la_fin_de_2020', label: 'Activité Cumulée en mCi jusqu\'à la fin de 2020', sectionId: 'i1_avant_2021', type: 'number', order: 3 },
  { id: 'statut_clinique_global', label: 'Statut clinique global', sectionId: 'i1_avant_2021', type: 'enum', order: 4, options: opt('RC clinique', 'RP clinique', 'RS clinique', 'PD clinique') },
  { id: 'statut_biologique_global', label: 'Statut Biologique global', sectionId: 'i1_avant_2021', type: 'enum', order: 5, options: opt('RC biologique', 'RP biologique', 'RS biologique', 'PD biologique') },
  { id: 'statut_isotopique_global', label: 'Statut Isotopique global', sectionId: 'i1_avant_2021', type: 'enum', order: 6, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'statut_radiologique_global', label: 'Statut Radiologique global', sectionId: 'i1_avant_2021', type: 'enum', order: 7, options: opt('RC radiologique', 'RP radiologique', 'RS radiologique', 'PD radiologique') },
  { id: 'i1_2020', label: 'I1 ≥ 2020', sectionId: 'i1_avant_2021', type: 'enum', order: 8, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'date_i1', label: 'Date I1', sectionId: 'cure_i1', type: 'date', order: 1 },
  { id: 'modalites_de_stimulation', label: 'Modalités de Stimulation', sectionId: 'cure_i1', type: 'enum', order: 2, options: opt('Endogène', 'Exogène', 'Mixte') },
  { id: 'duree_du_sevrage_de_l_thyroxine', label: 'Durée du Sevrage de L-Thyroxine', sectionId: 'cure_i1', type: 'enum', order: 3, options: opt('1 semaine', '2 semaines', '3 semaines', '4 semaines', '5 semaines', '6 semaines', '> 6 semaines') },
  { id: 'tshrh', label: 'TSHrh', sectionId: 'cure_i1', type: 'enum', order: 4, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'bilan_thyroidien_externe_2', label: 'Bilan Thyroïdien (Externe)', sectionId: 'cure_i1', type: 'text', order: 5 },
  { id: 'tshus_ui_ml_3', label: 'TSHus µUI/ml', sectionId: 'cure_i1', type: 'number', order: 6 },
  { id: 'tg_ng_ml_sans_dilution_3', label: 'Tg ng/ml (sans dilution)', sectionId: 'cure_i1', type: 'number', order: 7 },
  { id: 'tg_ng_ml_exact_3', label: 'Tg ng/ml (Exact)', sectionId: 'cure_i1', type: 'number', order: 8 },
  { id: 'ac_anti_tg_ui_ml_3', label: 'Ac Anti-Tg UI/ml', sectionId: 'cure_i1', type: 'number', order: 9 },
  { id: 'titre_des_anti_tg_si_faite_3', label: 'Titre des Anti-Tg (si faite)', sectionId: 'cure_i1', type: 'number', order: 10 },
  { id: 'bilan_thyroidien_ria_2', label: 'Bilan Thyroïdien (RIA)', sectionId: 'cure_i1', type: 'text', order: 11 },
  { id: 'tshus_ui_ml_4', label: 'TSHus µUI/ml', sectionId: 'cure_i1', type: 'number', order: 12 },
  { id: 'tg_ng_ml_sans_dilution_4', label: 'Tg ng/ml (sans dilution)', sectionId: 'cure_i1', type: 'number', order: 13 },
  { id: 'tg_ng_ml_exact_4', label: 'Tg ng/ml (Exact)', sectionId: 'cure_i1', type: 'number', order: 14 },
  { id: 'ac_anti_tg_ui_ml_4', label: 'Ac Anti-Tg UI/ml', sectionId: 'cure_i1', type: 'number', order: 15 },
  { id: 'titre_des_anti_tg_si_faite_4', label: 'Titre des Anti-Tg (si faite)', sectionId: 'cure_i1', type: 'number', order: 16 },
  { id: 'corticotherapie', label: 'Corticothérapie', sectionId: 'cure_i1', type: 'enum', order: 17, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'anti_emetique', label: 'Anti-émétique', sectionId: 'cure_i1', type: 'enum', order: 18, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'garde_malade', label: 'Garde Malade', sectionId: 'cure_i1', type: 'enum', order: 19, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'sonde_urinaire', label: 'Sonde Urinaire', sectionId: 'cure_i1', type: 'enum', order: 20, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'actitvite_en_mci', label: 'Actitvité en mCi', sectionId: 'cure_i1', type: 'number', order: 21 },
  { id: 'duree_d_hospitalisation_en_jours', label: 'Durée d\'Hospitalisation en Jours', sectionId: 'cure_i1', type: 'number', order: 22 },
  { id: 'tolerance_clinique', label: 'Tolérance Clinique', sectionId: 'cure_i1', type: 'multi', order: 23, options: opt('Asymptomatique', 'Œdème cervical', 'Nausées', 'Vomissements', 'Céphalées', 'Sialadénite', 'Gastralgies', 'Douleurs osseuses', 'Dyspnée', 'Autres', 'Non précisé') },
  { id: 'realisation_de_bpt_1', label: 'Réalisation de BPT 1', sectionId: 'cure_i1', type: 'enum', order: 24, options: opt('Oui', 'Non') },
  { id: 'protocole', label: 'Protocole', sectionId: 'cure_i1', type: 'enum', order: 25, options: opt('CES', 'CES + SPECT-CT', 'CES + SPECT') },
  { id: 'ces', label: 'CES', sectionId: 'cure_i1', type: 'text', order: 26 },
  { id: 'presence_de_reliquat_iodo_fixant', label: 'Présence de Reliquat Iodo-fixant', sectionId: 'cure_i1', type: 'enum', order: 27, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'rt_siege', label: 'RT Siège', sectionId: 'cure_i1', type: 'multi', order: 28, options: opt('Droit', 'Gauche', 'Canal thyréoglosse', 'CB') },
  { id: 'rt_nombre', label: 'RT Nombre', sectionId: 'cure_i1', type: 'number', order: 29 },
  { id: 'rt_intensite', label: 'RT Intensité', sectionId: 'cure_i1', type: 'enum', order: 30, options: opt('Absence', 'Discrète', 'Modérée', 'Intense', 'Très intense') },
  { id: 'presence_de_metastases_pulmonaires_iodo_fixants', label: 'Présence de Métastases Pulmonaires iodo-fixants', sectionId: 'cure_i1', type: 'enum', order: 31, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'mp_nombre', label: 'MP Nombre', sectionId: 'cure_i1', type: 'number', order: 32 },
  { id: 'mp_intensite', label: 'MP Intensité', sectionId: 'cure_i1', type: 'enum', order: 33, options: opt('Absence', 'Discrète', 'Modérée', 'Intense', 'Très intense') },
  { id: 'presence_de_metastases_osseuses', label: 'Présence de Métastases Osseuses', sectionId: 'cure_i1', type: 'enum', order: 34, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'mo_nombre', label: 'MO Nombre', sectionId: 'cure_i1', type: 'number', order: 35 },
  { id: 'mo_intensite', label: 'MO Intensité', sectionId: 'cure_i1', type: 'enum', order: 36, options: opt('Absence', 'Discrète', 'Modérée', 'Intense', 'Très intense') },
  { id: 'rachis_2', label: 'Rachis', sectionId: 'cure_i1', type: 'enum', order: 37, options: opt('Oui', 'Non') },
  { id: 'pelvis_2', label: 'Pelvis', sectionId: 'cure_i1', type: 'enum', order: 38, options: opt('Oui', 'Non') },
  { id: 'thorax_2', label: 'Thorax', sectionId: 'cure_i1', type: 'enum', order: 39, options: opt('Oui', 'Non') },
  { id: 'crane_2', label: 'Crâne', sectionId: 'cure_i1', type: 'enum', order: 40, options: opt('Oui', 'Non') },
  { id: 'membres_2', label: 'Membres', sectionId: 'cure_i1', type: 'enum', order: 41, options: opt('Oui', 'Non') },
  { id: 'spect_ct', label: 'SPECT-CT', sectionId: 'cure_i1', type: 'text', order: 42 },
  { id: 'spect_ct_champs', label: 'SPECT-CT : Champs', sectionId: 'cure_i1', type: 'multi', order: 43 },
  { id: 'reliquat_i_a_la_tdm', label: 'Reliquat I(+) à la TDM', sectionId: 'cure_i1', type: 'multi', order: 44 },
  { id: 'reliquat_i_a_la_tdm_2', label: 'Reliquat I(-) à la TDM', sectionId: 'cure_i1', type: 'multi', order: 45 },
  { id: 'ganglions_i_a_la_tdm', label: 'Ganglions I(+) à la TDM', sectionId: 'cure_i1', type: 'multi', order: 46 },
  { id: 'ganglions_i_a_la_tdm_2', label: 'Ganglions I(-) à la TDM', sectionId: 'cure_i1', type: 'multi', order: 47 },
  { id: 'meta_pulm_i_a_la_tdm', label: 'Méta Pulm I(+) à la TDM', sectionId: 'cure_i1', type: 'multi', order: 48 },
  { id: 'meta_pulm_i_a_la_tdm_2', label: 'Méta Pulm I(-) à la TDM', sectionId: 'cure_i1', type: 'multi', order: 49 },
  { id: 'meta_osseuses_i', label: 'Méta Osseuses I(+)', sectionId: 'cure_i1', type: 'multi', order: 50, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'mo_i_nombre', label: 'MO I(+) Nombre', sectionId: 'cure_i1', type: 'number', order: 51 },
  { id: 'rachis_3', label: 'Rachis', sectionId: 'cure_i1', type: 'enum', order: 52, options: opt('Oui', 'Non') },
  { id: 'pelvis_3', label: 'Pelvis', sectionId: 'cure_i1', type: 'enum', order: 53, options: opt('Oui', 'Non') },
  { id: 'thorax_3', label: 'Thorax', sectionId: 'cure_i1', type: 'enum', order: 54, options: opt('Oui', 'Non') },
  { id: 'crane_3', label: 'Crâne', sectionId: 'cure_i1', type: 'enum', order: 55, options: opt('Oui', 'Non') },
  { id: 'membres_3', label: 'Membres', sectionId: 'cure_i1', type: 'enum', order: 56, options: opt('Oui', 'Non') },
  { id: 'semiologie_tdm', label: 'Sémiologie TDM', sectionId: 'cure_i1', type: 'multi', order: 57, options: opt('Non documentée', 'Absente', 'Sans traduction CT', 'Ostéolytique', 'Mixte', 'Ostéocondensante', 'Extension aux tissus mous', 'Compliquée (fracture, compression médullaire)') },
  { id: 'gd_diametre_lesion_cible_1_en_cm', label: 'Gd Diamètre Lésion Cible 1 en cm', sectionId: 'cure_i1', type: 'number', order: 58 },
  { id: 'gd_diametre_lesion_cible_2_en_cm', label: 'Gd Diamètre Lésion Cible 2 en cm', sectionId: 'cure_i1', type: 'number', order: 59 },
  { id: 'meta_osseuses_i_2', label: 'Méta Osseuses I(-)', sectionId: 'cure_i1', type: 'multi', order: 60, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'mo_i_nombre_2', label: 'MO I(-) Nombre', sectionId: 'cure_i1', type: 'number', order: 61 },
  { id: 'rachis_4', label: 'Rachis', sectionId: 'cure_i1', type: 'enum', order: 62, options: opt('Oui', 'Non') },
  { id: 'pelvis_4', label: 'Pelvis', sectionId: 'cure_i1', type: 'enum', order: 63, options: opt('Oui', 'Non') },
  { id: 'thorax_4', label: 'Thorax', sectionId: 'cure_i1', type: 'enum', order: 64, options: opt('Oui', 'Non') },
  { id: 'crane_4', label: 'Crâne', sectionId: 'cure_i1', type: 'enum', order: 65, options: opt('Oui', 'Non') },
  { id: 'membres_4', label: 'Membres', sectionId: 'cure_i1', type: 'enum', order: 66, options: opt('Oui', 'Non') },
  { id: 'semiologie_tdm_2', label: 'Sémiologie TDM', sectionId: 'cure_i1', type: 'multi', order: 67, options: opt('Non documentée', 'Absente', 'Sans traduction CT', 'Ostéolytique', 'Mixte', 'Ostéocondensante', 'Extension aux tissus mous', 'Compliquée (fracture, compression médullaire)') },
  { id: 'gd_diametre_lesion_cible_1_en_cm_2', label: 'Gd Diamètre Lésion Cible 1 en cm', sectionId: 'cure_i1', type: 'number', order: 68 },
  { id: 'gd_diametre_lesion_cible_2_en_cm_2', label: 'Gd Diamètre Lésion Cible 2 en cm', sectionId: 'cure_i1', type: 'number', order: 69 },
  { id: 'autres_lesions_i', label: 'Autres Lésions I(+)', sectionId: 'cure_i1', type: 'multi', order: 70, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'autres_lesions_i_2', label: 'Autres Lésions I(-)', sectionId: 'cure_i1', type: 'multi', order: 71, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'eval1', label: 'Eval1', sectionId: 'cure_i1', type: 'enum', order: 72, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'etat_general_2', label: 'Etat Général', sectionId: 'cure_i1', type: 'text', order: 73 },
  { id: 'autonomie_2', label: 'Autonomie', sectionId: 'cure_i1', type: 'enum', order: 74, options: opt('Oui', 'Non') },
  { id: 'deambulation_2', label: 'Déambulation', sectionId: 'cure_i1', type: 'enum', order: 75, options: opt('Conservée', 'Ralentie', 'avec canne', 'avec béquilles', 'sur fauteuil roulant', 'Patient(e) alité(e)') },
  { id: 'score_de_karnofsky_2', label: 'Score de Karnofsky', sectionId: 'cure_i1', type: 'enum', order: 76, options: opt('100-90', '80-70', '60-50', '40-30', '≤ 20') },
  { id: 'douleur_2', label: 'Douleur', sectionId: 'cure_i1', type: 'enum', order: 77, options: opt('Oui', 'Non') },
  { id: 'nombre_de_sites_2', label: 'Nombre de Sites', sectionId: 'cure_i1', type: 'number', order: 78 },
  { id: 'intensite_2', label: 'Intensité', sectionId: 'cure_i1', type: 'enum', order: 79, options: opt('Absence', 'Légère', 'Modérée', 'Sévère') },
  { id: 'eva_2', label: 'EVA', sectionId: 'cure_i1', type: 'number', order: 80 },
  { id: 'impotence_fonctionnelle_2', label: 'Impotence Fonctionnelle', sectionId: 'cure_i1', type: 'enum', order: 81, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'trouble_neurologique_2', label: 'Trouble Neurologique', sectionId: 'cure_i1', type: 'multi', order: 82, options: opt('Absent', 'Paresthésie-Hypoesthésie', 'Douleur radiculaire', 'Faiblesse musculaire', 'Parésie-Paralysie', 'Amyotrophie', 'Incontinence urinaire') },
  { id: 'sous_l_thyroxine_3', label: 'sous L-Thyroxine', sectionId: 'cure_i1', type: 'enum', order: 83, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'degres_de_freinage_2', label: 'Degrès de Freinage', sectionId: 'cure_i1', type: 'enum', order: 84, options: opt('Bien freiné', 'Mal freiné', 'en hypothyroïdie', 'Non précisé') },
  { id: 'bilan_thyroidien_ria_3', label: 'Bilan Thyroïdien (RIA)', sectionId: 'cure_i1', type: 'text', order: 85 },
  { id: 'tshus_ui_ml_5', label: 'TSHus µUI/ml', sectionId: 'cure_i1', type: 'number', order: 86 },
  { id: 'tg_ng_ml_sans_dilution_5', label: 'Tg ng/ml (sans dilution)', sectionId: 'cure_i1', type: 'number', order: 87 },
  { id: 'tg_ng_ml_exact_5', label: 'Tg ng/ml (Exact)', sectionId: 'cure_i1', type: 'number', order: 88 },
  { id: 'ac_anti_tg_ui_ml_5', label: 'Ac Anti-Tg UI/ml', sectionId: 'cure_i1', type: 'number', order: 89 },
  { id: 'titre_des_anti_tg_si_faite_5', label: 'Titre des Anti-Tg (si faite)', sectionId: 'cure_i1', type: 'number', order: 90 },
  { id: 'ec_post_i1', label: 'EC post I1', sectionId: 'cure_i1', type: 'multi', order: 91, options: opt('Non faite', 'RAS', 'Reliquat thyroïdien', 'Nodule thyroïdien', 'Lobe restant', 'Adénopathies', 'Extension extra-thyroïdienne') },
  { id: 'tdm_ctap', label: 'TDM CTAP', sectionId: 'cure_i1', type: 'enum', order: 92, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_tdm_2', label: 'Résultats TDM', sectionId: 'cure_i1', type: 'multi', order: 93 },
  { id: 'irm_cerebro_medullaire_2', label: 'IRM Cérébro-Médullaire', sectionId: 'cure_i1', type: 'enum', order: 94, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_irm_2', label: 'Résultats IRM', sectionId: 'cure_i1', type: 'multi', order: 95 },
  { id: 'scintigraphie_osseuse_2', label: 'Scintigraphie Osseuse', sectionId: 'cure_i1', type: 'enum', order: 96, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_so_3', label: 'Résultats SO', sectionId: 'cure_i1', type: 'number', order: 97 },
  { id: 'tep_fdg_2', label: 'TEP FDG', sectionId: 'cure_i1', type: 'enum', order: 98, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_fdg_2', label: 'Résultats FDG', sectionId: 'cure_i1', type: 'multi', order: 99 },
  { id: 'autre', label: 'Autre', sectionId: 'cure_i1', type: 'text', order: 100 },
  { id: 'efr', label: 'EFR', sectionId: 'cure_i1', type: 'enum', order: 101, options: opt('Non faite', 'Normale', 'Sd restrictif', 'Sd obstructif', 'Sd mixte') },
  { id: 'fns', label: 'FNS', sectionId: 'cure_i1', type: 'enum', order: 102, options: opt('Non faite', 'Normale', 'Anémie', 'Leucopénie', 'Thrombopénie') },
  { id: 'bilan_renal', label: 'Bilan Rénal', sectionId: 'cure_i1', type: 'enum', order: 103, options: opt('Non fait', 'Normal', 'IR légère', 'IR modérée', 'IR sévère', 'IR terminale') },
  { id: 'dmo', label: 'DMO', sectionId: 'cure_i1', type: 'enum', order: 104, options: opt('Non faite', 'Normale', 'Ostéopénie', 'Ostéoporose') },
  { id: 'evaluation_i1', label: 'Evaluation I1', sectionId: 'cure_i1', type: 'enum', order: 105, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'i2', label: 'I2', sectionId: 'cure_i2', type: 'enum', order: 1, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'date_i2', label: 'Date I2', sectionId: 'cure_i2', type: 'date', order: 2 },
  { id: 'modalites_de_stimulation_2', label: 'Modalités de Stimulation', sectionId: 'cure_i2', type: 'enum', order: 3, options: opt('Endogène', 'Exogène', 'Mixte') },
  { id: 'duree_du_sevrage_de_l_thyroxine_2', label: 'Durée du Sevrage de L-Thyroxine', sectionId: 'cure_i2', type: 'enum', order: 4, options: opt('1 semaine', '2 semaines', '3 semaines', '4 semaines', '5 semaines', '6 semaines', '> 6 semaines') },
  { id: 'tshrh_2', label: 'TSHrh', sectionId: 'cure_i2', type: 'enum', order: 5, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'bilan_thyroidien_externe_3', label: 'Bilan Thyroïdien (Externe)', sectionId: 'cure_i2', type: 'text', order: 6 },
  { id: 'tshus_ui_ml_6', label: 'TSHus µUI/ml', sectionId: 'cure_i2', type: 'number', order: 7 },
  { id: 'tg_ng_ml_sans_dilution_6', label: 'Tg ng/ml (sans dilution)', sectionId: 'cure_i2', type: 'number', order: 8 },
  { id: 'tg_ng_ml_exact_6', label: 'Tg ng/ml (Exact)', sectionId: 'cure_i2', type: 'number', order: 9 },
  { id: 'ac_anti_tg_ui_ml_6', label: 'Ac Anti-Tg UI/ml', sectionId: 'cure_i2', type: 'number', order: 10 },
  { id: 'titre_des_anti_tg_si_faite_6', label: 'Titre des Anti-Tg (si faite)', sectionId: 'cure_i2', type: 'number', order: 11 },
  { id: 'bilan_thyroidien_ria_4', label: 'Bilan Thyroïdien (RIA)', sectionId: 'cure_i2', type: 'text', order: 12 },
  { id: 'tshus_ui_ml_7', label: 'TSHus µUI/ml', sectionId: 'cure_i2', type: 'number', order: 13 },
  { id: 'tg_ng_ml_sans_dilution_7', label: 'Tg ng/ml (sans dilution)', sectionId: 'cure_i2', type: 'number', order: 14 },
  { id: 'tg_ng_ml_exact_7', label: 'Tg ng/ml (Exact)', sectionId: 'cure_i2', type: 'number', order: 15 },
  { id: 'ac_anti_tg_ui_ml_7', label: 'Ac Anti-Tg UI/ml', sectionId: 'cure_i2', type: 'number', order: 16 },
  { id: 'titre_des_anti_tg_si_faite_7', label: 'Titre des Anti-Tg (si faite)', sectionId: 'cure_i2', type: 'number', order: 17 },
  { id: 'corticotherapie_2', label: 'Corticothérapie', sectionId: 'cure_i2', type: 'enum', order: 18, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'anti_emetique_2', label: 'Anti-émétique', sectionId: 'cure_i2', type: 'enum', order: 19, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'garde_malade_2', label: 'Garde Malade', sectionId: 'cure_i2', type: 'enum', order: 20, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'sonde_urinaire_2', label: 'Sonde Urinaire', sectionId: 'cure_i2', type: 'enum', order: 21, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'actitvite_en_mci_2', label: 'Actitvité en mCi', sectionId: 'cure_i2', type: 'number', order: 22 },
  { id: 'duree_d_hospitalisation_en_jours_2', label: 'Durée d\'Hospitalisation en Jours', sectionId: 'cure_i2', type: 'number', order: 23 },
  { id: 'tolerance_clinique_2', label: 'Tolérance Clinique', sectionId: 'cure_i2', type: 'multi', order: 24, options: opt('Asymptomatique', 'Œdème cervical', 'Nausées', 'Vomissements', 'Céphalées', 'Sialadénite', 'Gastralgies', 'Douleurs osseuses', 'Dyspnée', 'Autres', 'Non précisé') },
  { id: 'realisation_de_bpt_2', label: 'Réalisation de BPT 2', sectionId: 'cure_i2', type: 'enum', order: 25, options: opt('Oui', 'Non') },
  { id: 'protocole_2', label: 'Protocole', sectionId: 'cure_i2', type: 'enum', order: 26, options: opt('CES', 'CES + SPECT-CT', 'CES + SPECT') },
  { id: 'ces_2', label: 'CES', sectionId: 'cure_i2', type: 'text', order: 27 },
  { id: 'presence_de_reliquat_iodo_fixant_2', label: 'Présence de Reliquat Iodo-fixant', sectionId: 'cure_i2', type: 'enum', order: 28, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'rt_siege_2', label: 'RT Siège', sectionId: 'cure_i2', type: 'multi', order: 29, options: opt('Droit', 'Gauche', 'Canal thyréoglosse', 'CB') },
  { id: 'rt_nombre_2', label: 'RT Nombre', sectionId: 'cure_i2', type: 'number', order: 30 },
  { id: 'rt_intensite_2', label: 'RT Intensité', sectionId: 'cure_i2', type: 'enum', order: 31, options: opt('Absence', 'Discrète', 'Modérée', 'Intense', 'Très intense') },
  { id: 'presence_de_metastases_pulmonaires_iodo_fixants_2', label: 'Présence de Métastases Pulmonaires iodo-fixants', sectionId: 'cure_i2', type: 'enum', order: 32, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'mp_nombre_2', label: 'MP Nombre', sectionId: 'cure_i2', type: 'number', order: 33 },
  { id: 'mp_intensite_2', label: 'MP Intensité', sectionId: 'cure_i2', type: 'enum', order: 34, options: opt('Absence', 'Discrète', 'Modérée', 'Intense', 'Très intense') },
  { id: 'presence_de_metastases_osseuses_2', label: 'Présence de Métastases Osseuses', sectionId: 'cure_i2', type: 'enum', order: 35, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'mo_nombre_2', label: 'MO Nombre', sectionId: 'cure_i2', type: 'number', order: 36 },
  { id: 'mo_intensite_2', label: 'MO Intensité', sectionId: 'cure_i2', type: 'enum', order: 37, options: opt('Absence', 'Discrète', 'Modérée', 'Intense', 'Très intense') },
  { id: 'rachis_5', label: 'Rachis', sectionId: 'cure_i2', type: 'enum', order: 38, options: opt('Oui', 'Non') },
  { id: 'pelvis_5', label: 'Pelvis', sectionId: 'cure_i2', type: 'enum', order: 39, options: opt('Oui', 'Non') },
  { id: 'thorax_5', label: 'Thorax', sectionId: 'cure_i2', type: 'enum', order: 40, options: opt('Oui', 'Non') },
  { id: 'crane_5', label: 'Crâne', sectionId: 'cure_i2', type: 'enum', order: 41, options: opt('Oui', 'Non') },
  { id: 'membres_5', label: 'Membres', sectionId: 'cure_i2', type: 'enum', order: 42, options: opt('Oui', 'Non') },
  { id: 'spect_ct_2', label: 'SPECT-CT', sectionId: 'cure_i2', type: 'text', order: 43 },
  { id: 'spect_ct_champs_2', label: 'SPECT-CT : Champs', sectionId: 'cure_i2', type: 'text', order: 44 },
  { id: 'reliquat_i_a_la_tdm_3', label: 'Reliquat I(+) à la TDM', sectionId: 'cure_i2', type: 'text', order: 45 },
  { id: 'reliquat_i_a_la_tdm_4', label: 'Reliquat I(-) à la TDM', sectionId: 'cure_i2', type: 'multi', order: 46 },
  { id: 'ganglions_i_a_la_tdm_3', label: 'Ganglions I(+) à la TDM', sectionId: 'cure_i2', type: 'multi', order: 47 },
  { id: 'ganglions_i_a_la_tdm_4', label: 'Ganglions I(-) à la TDM', sectionId: 'cure_i2', type: 'multi', order: 48 },
  { id: 'meta_pulm_i_a_la_tdm_3', label: 'Méta Pulm I(+) à la TDM', sectionId: 'cure_i2', type: 'multi', order: 49 },
  { id: 'meta_pulm_i_a_la_tdm_4', label: 'Méta Pulm I(-) à la TDM', sectionId: 'cure_i2', type: 'multi', order: 50 },
  { id: 'meta_osseuses_i_3', label: 'Méta Osseuses I(+)', sectionId: 'cure_i2', type: 'multi', order: 51, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'mo_i_nombre_3', label: 'MO I(+) Nombre', sectionId: 'cure_i2', type: 'number', order: 52 },
  { id: 'rachis_6', label: 'Rachis', sectionId: 'cure_i2', type: 'enum', order: 53, options: opt('Oui', 'Non') },
  { id: 'pelvis_6', label: 'Pelvis', sectionId: 'cure_i2', type: 'enum', order: 54, options: opt('Oui', 'Non') },
  { id: 'thorax_6', label: 'Thorax', sectionId: 'cure_i2', type: 'enum', order: 55, options: opt('Oui', 'Non') },
  { id: 'crane_6', label: 'Crâne', sectionId: 'cure_i2', type: 'enum', order: 56, options: opt('Oui', 'Non') },
  { id: 'membres_6', label: 'Membres', sectionId: 'cure_i2', type: 'enum', order: 57, options: opt('Oui', 'Non') },
  { id: 'semiologie_tdm_3', label: 'Sémiologie TDM', sectionId: 'cure_i2', type: 'multi', order: 58, options: opt('Non documentée', 'Absente', 'Sans traduction CT', 'Ostéolytique', 'Mixte', 'Ostéocondensante', 'Extension aux tissus mous', 'Compliquée (fracture, compression médullaire)') },
  { id: 'gd_diametre_lesion_cible_1_en_cm_3', label: 'Gd Diamètre Lésion Cible 1 en cm', sectionId: 'cure_i2', type: 'number', order: 59 },
  { id: 'gd_diametre_lesion_cible_2_en_cm_3', label: 'Gd Diamètre Lésion Cible 2 en cm', sectionId: 'cure_i2', type: 'number', order: 60 },
  { id: 'meta_osseuses_i_4', label: 'Méta Osseuses I(-)', sectionId: 'cure_i2', type: 'multi', order: 61, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'mo_i_nombre_4', label: 'MO I(-) Nombre', sectionId: 'cure_i2', type: 'number', order: 62 },
  { id: 'rachis_7', label: 'Rachis', sectionId: 'cure_i2', type: 'enum', order: 63, options: opt('Oui', 'Non') },
  { id: 'pelvis_7', label: 'Pelvis', sectionId: 'cure_i2', type: 'enum', order: 64, options: opt('Oui', 'Non') },
  { id: 'thorax_7', label: 'Thorax', sectionId: 'cure_i2', type: 'enum', order: 65, options: opt('Oui', 'Non') },
  { id: 'crane_7', label: 'Crâne', sectionId: 'cure_i2', type: 'enum', order: 66, options: opt('Oui', 'Non') },
  { id: 'membres_7', label: 'Membres', sectionId: 'cure_i2', type: 'enum', order: 67, options: opt('Oui', 'Non') },
  { id: 'semiologie_tdm_4', label: 'Sémiologie TDM', sectionId: 'cure_i2', type: 'multi', order: 68, options: opt('Non documentée', 'Absente', 'Sans traduction CT', 'Ostéolytique', 'Mixte', 'Ostéocondensante', 'Extension aux tissus mous', 'Compliquée (fracture, compression médullaire)') },
  { id: 'gd_diametre_lesion_cible_1_en_cm_4', label: 'Gd Diamètre Lésion Cible 1 en cm', sectionId: 'cure_i2', type: 'number', order: 69 },
  { id: 'gd_diametre_lesion_cible_2_en_cm_4', label: 'Gd Diamètre Lésion Cible 2 en cm', sectionId: 'cure_i2', type: 'number', order: 70 },
  { id: 'autres_lesions_i_3', label: 'Autres Lésions I(+)', sectionId: 'cure_i2', type: 'multi', order: 71, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'autres_lesions_i_4', label: 'Autres Lésions I(-)', sectionId: 'cure_i2', type: 'multi', order: 72, options: opt('Absence', 'Sans traduction CT', 'Infra cm', 'Supra cm', 'Unilatéral', 'Bilatéral') },
  { id: 'eval_2', label: 'Eval 2', sectionId: 'cure_i2', type: 'enum', order: 73, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'etat_general_3', label: 'Etat Général', sectionId: 'cure_i2', type: 'text', order: 74 },
  { id: 'autonomie_3', label: 'Autonomie', sectionId: 'cure_i2', type: 'enum', order: 75, options: opt('Oui', 'Non') },
  { id: 'deambulation_3', label: 'Déambulation', sectionId: 'cure_i2', type: 'enum', order: 76, options: opt('Conservée', 'Ralentie', 'avec canne', 'avec béquilles', 'sur fauteuil roulant', 'Patient(e) alité(e)') },
  { id: 'score_de_karnofsky_3', label: 'Score de Karnofsky', sectionId: 'cure_i2', type: 'enum', order: 77, options: opt('100-90', '80-70', '60-50', '40-30', '≤ 20') },
  { id: 'douleur_3', label: 'Douleur', sectionId: 'cure_i2', type: 'enum', order: 78, options: opt('Oui', 'Non') },
  { id: 'nombre_de_sites_3', label: 'Nombre de Sites', sectionId: 'cure_i2', type: 'number', order: 79 },
  { id: 'intensite_3', label: 'Intensité', sectionId: 'cure_i2', type: 'enum', order: 80, options: opt('Absence', 'Légère', 'Modérée', 'Sévère') },
  { id: 'eva_3', label: 'EVA', sectionId: 'cure_i2', type: 'number', order: 81 },
  { id: 'impotence_fonctionnelle_3', label: 'Impotence Fonctionnelle', sectionId: 'cure_i2', type: 'enum', order: 82, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'trouble_neurologique_3', label: 'Trouble Neurologique', sectionId: 'cure_i2', type: 'multi', order: 83, options: opt('Absent', 'Paresthésie-Hypoesthésie', 'Douleur radiculaire', 'Faiblesse musculaire', 'Parésie-Paralysie', 'Amyotrophie', 'Incontinence urinaire') },
  { id: 'sous_l_thyroxine_4', label: 'sous L-Thyroxine', sectionId: 'cure_i2', type: 'enum', order: 84, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'degres_de_freinage_3', label: 'Degrès de Freinage', sectionId: 'cure_i2', type: 'enum', order: 85, options: opt('Bien freiné', 'Mal freiné', 'en hypothyroïdie', 'Non précisé') },
  { id: 'bilan_thyroidien_ria_5', label: 'Bilan Thyroïdien (RIA)', sectionId: 'cure_i2', type: 'text', order: 86 },
  { id: 'tshus_ui_ml_8', label: 'TSHus µUI/ml', sectionId: 'cure_i2', type: 'number', order: 87 },
  { id: 'tg_ng_ml_sans_dilution_8', label: 'Tg ng/ml (sans dilution)', sectionId: 'cure_i2', type: 'number', order: 88 },
  { id: 'tg_ng_ml_exact_8', label: 'Tg ng/ml (Exact)', sectionId: 'cure_i2', type: 'number', order: 89 },
  { id: 'ac_anti_tg_ui_ml_8', label: 'Ac Anti-Tg UI/ml', sectionId: 'cure_i2', type: 'number', order: 90 },
  { id: 'titre_des_anti_tg_si_faite_8', label: 'Titre des Anti-Tg (si faite)', sectionId: 'cure_i2', type: 'number', order: 91 },
  { id: 'ec_post_i1_2', label: 'EC post I1', sectionId: 'cure_i2', type: 'multi', order: 92, options: opt('Non faite', 'RAS', 'Reliquat thyroïdien', 'Nodule thyroïdien', 'Lobe restant', 'Adénopathies', 'Extension extra-thyroïdienne') },
  { id: 'tdm_ctap_2', label: 'TDM CTAP', sectionId: 'cure_i2', type: 'enum', order: 93, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_tdm_3', label: 'Résultats TDM', sectionId: 'cure_i2', type: 'multi', order: 94 },
  { id: 'irm_cerebro_medullaire_3', label: 'IRM Cérébro-Médullaire', sectionId: 'cure_i2', type: 'enum', order: 95, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_irm_3', label: 'Résultats IRM', sectionId: 'cure_i2', type: 'text', order: 96 },
  { id: 'scintigraphie_osseuse_3', label: 'Scintigraphie Osseuse', sectionId: 'cure_i2', type: 'enum', order: 97, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_so_4', label: 'Résultats SO', sectionId: 'cure_i2', type: 'number', order: 98 },
  { id: 'tep_fdg_3', label: 'TEP FDG', sectionId: 'cure_i2', type: 'enum', order: 99, options: opt('Non documentée', 'Faite', 'Non faite') },
  { id: 'resultats_fdg_3', label: 'Résultats FDG', sectionId: 'cure_i2', type: 'text', order: 100 },
  { id: 'autre_2', label: 'Autre', sectionId: 'cure_i2', type: 'text', order: 101 },
  { id: 'efr_2', label: 'EFR', sectionId: 'cure_i2', type: 'enum', order: 102, options: opt('Non faite', 'Normale', 'Sd restrictif', 'Sd obstructif', 'Sd mixte') },
  { id: 'fns_2', label: 'FNS', sectionId: 'cure_i2', type: 'enum', order: 103, options: opt('Non faite', 'Normale', 'Anémie', 'Leucopénie', 'Thrombopénie') },
  { id: 'bilan_renal_2', label: 'Bilan Rénal', sectionId: 'cure_i2', type: 'enum', order: 104, options: opt('Non fait', 'Normal', 'IR légère', 'IR modérée', 'IR sévère', 'IR terminale') },
  { id: 'dmo_2', label: 'DMO', sectionId: 'cure_i2', type: 'enum', order: 105, options: opt('Non faite', 'Normale', 'Ostéopénie', 'Ostéoporose') },
  { id: 'evaluation_i2', label: 'Evaluation I2', sectionId: 'cure_i2', type: 'enum', order: 106, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'cures_iteratives', label: 'Cures Itératives', sectionId: 'cure_i3', type: 'text', order: 1 },
  { id: 'i3', label: 'I3', sectionId: 'cure_i3', type: 'enum', order: 2, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'date_i3', label: 'Date I3', sectionId: 'cure_i3', type: 'date', order: 3 },
  { id: 'tg_i3', label: 'Tg I3', sectionId: 'cure_i3', type: 'number', order: 4 },
  { id: 'activite_i3', label: 'Activité I3', sectionId: 'cure_i3', type: 'number', order: 5 },
  { id: 'bpt3', label: 'BPT3', sectionId: 'cure_i3', type: 'text', order: 6 },
  { id: 'clinique_post_i3', label: 'Clinique post I3', sectionId: 'cure_i3', type: 'text', order: 7 },
  { id: 'tg_post_i3', label: 'Tg post I3', sectionId: 'cure_i3', type: 'number', order: 8 },
  { id: 'tdm_post_i3', label: 'TDM post I3', sectionId: 'cure_i3', type: 'text', order: 9 },
  { id: 'eval_i3', label: 'Eval I3', sectionId: 'cure_i3', type: 'enum', order: 10, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'i4', label: 'I4', sectionId: 'cure_i3', type: 'enum', order: 11, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'date_i4', label: 'Date I4', sectionId: 'cure_i3', type: 'date', order: 12 },
  { id: 'tg_i4', label: 'Tg I4', sectionId: 'cure_i3', type: 'text', order: 13 },
  { id: 'activite_i4', label: 'Activité I4', sectionId: 'cure_i3', type: 'text', order: 14 },
  { id: 'bpt4', label: 'BPT4', sectionId: 'cure_i3', type: 'text', order: 15 },
  { id: 'clinique_post_i4', label: 'Clinique post I4', sectionId: 'cure_i3', type: 'text', order: 16 },
  { id: 'tg_post_i4', label: 'Tg post I4', sectionId: 'cure_i3', type: 'text', order: 17 },
  { id: 'tdm_post_i4', label: 'TDM post I4', sectionId: 'cure_i3', type: 'text', order: 18 },
  { id: 'eval_i4', label: 'Eval I4', sectionId: 'cure_i3', type: 'enum', order: 19, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'i5', label: 'I5', sectionId: 'cure_i4', type: 'enum', order: 1, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'date_i5', label: 'Date I5', sectionId: 'cure_i4', type: 'date', order: 2 },
  { id: 'tg_i5', label: 'Tg I5', sectionId: 'cure_i4', type: 'text', order: 3 },
  { id: 'activite_i5', label: 'Activité I5', sectionId: 'cure_i4', type: 'text', order: 4 },
  { id: 'bpt5', label: 'BPT5', sectionId: 'cure_i4', type: 'text', order: 5 },
  { id: 'clinique_post_i5', label: 'Clinique post I5', sectionId: 'cure_i4', type: 'text', order: 6 },
  { id: 'tg_post_i5', label: 'Tg post I5', sectionId: 'cure_i4', type: 'text', order: 7 },
  { id: 'tdm_post_i5', label: 'TDM post I5', sectionId: 'cure_i4', type: 'text', order: 8 },
  { id: 'eval_i5', label: 'Eval I5', sectionId: 'cure_i4', type: 'enum', order: 9, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'i6', label: 'I6', sectionId: 'cure_i5_i6', type: 'enum', order: 1, options: opt('Oui', 'Non', 'Non précisé') },
  { id: 'date_i6', label: 'Date I6', sectionId: 'cure_i5_i6', type: 'date', order: 2 },
  { id: 'tg_i6', label: 'Tg I6', sectionId: 'cure_i5_i6', type: 'text', order: 3 },
  { id: 'activite_i6', label: 'Activité I6', sectionId: 'cure_i5_i6', type: 'text', order: 4 },
  { id: 'bpt6', label: 'BPT6', sectionId: 'cure_i5_i6', type: 'text', order: 5 },
  { id: 'clinique_post_i6', label: 'Clinique post I6', sectionId: 'cure_i5_i6', type: 'text', order: 6 },
  { id: 'tg_post_i6', label: 'Tg post I6', sectionId: 'cure_i5_i6', type: 'text', order: 7 },
  { id: 'tdm_post_i6', label: 'TDM post I6', sectionId: 'cure_i5_i6', type: 'text', order: 8 },
  { id: 'eval_i6', label: 'Eval I6', sectionId: 'cure_i5_i6', type: 'enum', order: 9, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'suivi', label: 'Suivi', sectionId: 'suivi_devenir', type: 'text', order: 1 },
  { id: 'eval_globale', label: 'Eval globale', sectionId: 'suivi_devenir', type: 'enum', order: 2, options: opt('RC', 'RP', 'RS', 'PD') },
  { id: 'duree_totale_de_suivi_en_ira_mois', label: 'Durée totale de Suivi en IRA (mois)', sectionId: 'suivi_devenir', type: 'number', order: 3 },
  { id: 'antalgiques', label: 'Antalgiques', sectionId: 'suivi_devenir', type: 'enum', order: 4, options: opt('Non', 'C1', 'C2', 'C3') },
  { id: 'rte', label: 'RTE', sectionId: 'suivi_devenir', type: 'enum', order: 5, options: opt('Oui', 'Non') },
  { id: 'bp_denosumab', label: 'BP/Dénosumab', sectionId: 'suivi_devenir', type: 'enum', order: 6, options: opt('Oui', 'Non') },
  { id: 'chirurgie_mo', label: 'Chirurgie MO', sectionId: 'suivi_devenir', type: 'enum', order: 7, options: opt('Oui', 'Non') },
  { id: 'tki', label: 'Tki', sectionId: 'suivi_devenir', type: 'enum', order: 8, options: opt('Non', 'Sorafénib', 'Lenvatinib', 'Cabozantinib') },
  { id: 'date_d_envoi_en_oncologie', label: 'Date d\'envoi en Oncologie', sectionId: 'suivi_devenir', type: 'date', order: 9 },
  { id: 'type_de_tki', label: 'Type de Tki', sectionId: 'suivi_devenir', type: 'enum', order: 10, options: opt('Non', 'Sorafénib', 'Lenvatinib', 'Cabozantinib') },
  { id: 'deces', label: 'Décès', sectionId: 'suivi_devenir', type: 'enum', order: 11, options: opt('Oui', 'Non') },
  { id: 'date_de_deces', label: 'date de décès', sectionId: 'suivi_devenir', type: 'date', order: 12 },
  { id: 'cure_i1_debit_dose_1h', label: 'Débit de dose à 1 heure (µSv/h)', sectionId: 'cure_i1', type: 'number', order: 106 },
  { id: 'cure_i1_debit_dose_sortie', label: 'Débit de dose à la sortie (µSv/h)', sectionId: 'cure_i1', type: 'number', order: 107 },
  { id: 'cure_i2_debit_dose_1h', label: 'Débit de dose à 1 heure (µSv/h)', sectionId: 'cure_i2', type: 'number', order: 107 },
  { id: 'cure_i2_debit_dose_sortie', label: 'Débit de dose à la sortie (µSv/h)', sectionId: 'cure_i2', type: 'number', order: 108 },
  { id: 'cure_i3_debit_dose_1h', label: 'Débit de dose à 1 heure (µSv/h)', sectionId: 'cure_i3', type: 'number', order: 20 },
  { id: 'cure_i3_debit_dose_sortie', label: 'Débit de dose à la sortie (µSv/h)', sectionId: 'cure_i3', type: 'number', order: 21 },
  { id: 'cure_i4_debit_dose_1h', label: 'Débit de dose à 1 heure (µSv/h)', sectionId: 'cure_i4', type: 'number', order: 10 },
  { id: 'cure_i4_debit_dose_sortie', label: 'Débit de dose à la sortie (µSv/h)', sectionId: 'cure_i4', type: 'number', order: 11 },
  { id: 'cure_i5_i6_debit_dose_1h', label: 'Débit de dose à 1 heure (µSv/h)', sectionId: 'cure_i5_i6', type: 'number', order: 10 },
  { id: 'cure_i5_i6_debit_dose_sortie', label: 'Débit de dose à la sortie (µSv/h)', sectionId: 'cure_i5_i6', type: 'number', order: 11 },
];

export function buildInitialSchema(): FormSchema {
  return {
    version: 1,
    updatedAt: Date.now(),
    sections: SECTIONS,
    fields: FIELDS,
  };
}
