import type { FieldDef, FormSchema, SectionDef, FieldOption } from './schema-types';

const opt = (...values: string[]): FieldOption[] => values.map((v) => ({ value: v }));

const WILAYAS: FieldOption[] = [
  'Adrar', 'Aïn Defla', 'Aïn Témouchent', 'Alger', 'Annaba', 'Batna', 'Béchar',
  'Béjaïa', 'Béni Abbès', 'Biskra', 'Blida', 'Bordj Badji Mokhtar',
  'Bordj Bou Arréridj', 'Bouira', 'Boumerdès', 'Chlef', 'Constantine', 'Djanet',
  'Djelfa', 'El Bayadh', "El M'Ghair", 'El Meniaa', 'El Oued', 'El Tarf',
  'Ghardaïa', 'Guelma', 'Illizi', 'In Guezzam', 'In Salah', 'Jijel', 'Khenchela',
  'Laghouat', "M'Sila", 'Mascara', 'Médéa', 'Mila', 'Mostaganem', 'Naâma',
  'Oran', 'Ouargla', 'Ouled Djellal', 'Oum El Bouaghi', 'Relizane', 'Saïda',
  'Sétif', 'Sidi Bel Abbès', 'Skikda', 'Souk Ahras', 'Tamanrasset', 'Tébessa',
  'Tiaret', 'Timimoun', 'Tindouf', 'Tipaza', 'Tissemsilt', 'Tizi Ouzou',
  'Tlemcen', 'Touggourt',
].map((v) => ({ value: v }));

const YNNP = opt('Oui', 'Non', 'Non précisé');

const SECTIONS: SectionDef[] = [
  { id: 'identification', label: 'Identification', order: 1, description: 'Données démographiques et coordonnées' },
  { id: 'atcd', label: 'Antécédents', order: 2, description: 'ATCD personnels, gynécologiques, familiaux' },
  { id: 'diagnostic_cdt', label: 'Diagnostic CDT', order: 3, description: 'Découverte, chirurgie, histologie, TNM' },
  { id: 'metastases', label: 'Métastases (M1)', order: 4, description: 'Sites, biopsie, chirurgie osseuse' },
  { id: 'bilan_extension', label: 'Bilan d\'extension', order: 5, description: 'Imagerie et biologie initiale' },
  { id: 'preparation_i1', label: 'Préparation I1', order: 6, description: 'État, EVA, freinage, EC pré-I1' },
  { id: 'cures_iode', label: 'Cures Iode 131', order: 7, description: 'Activités, BPT, évaluations (extensible)' },
  { id: 'suivi_global', label: 'Suivi global', order: 8, description: 'Statut clinique, biologique, isotopique, radiologique' },
  { id: 'devenir', label: 'Devenir', order: 9, description: 'Traitements complémentaires, décès' },
];

const FIELDS: FieldDef[] = [
  // ─────────── Identification ───────────
  { id: 'numero', label: 'Numéro de dossier', sectionId: 'identification', type: 'text', required: true, order: 1, hint: 'Format libre, ex : 001/24' },
  { id: 'nom', label: 'Nom', sectionId: 'identification', type: 'text', required: true, order: 2 },
  { id: 'prenoms', label: 'Prénoms', sectionId: 'identification', type: 'text', required: true, order: 3 },
  { id: 'sexe', label: 'Sexe', sectionId: 'identification', type: 'enum', options: opt('H', 'F'), required: true, order: 4 },
  { id: 'ddn', label: 'Date de naissance', sectionId: 'identification', type: 'date', order: 5 },
  { id: 'age_ouverture', label: 'Âge à l\'ouverture du dossier', sectionId: 'identification', type: 'number', min: 0, max: 120, order: 6 },
  { id: 'tel1', label: 'Téléphone 1', sectionId: 'identification', type: 'phone', order: 7 },
  { id: 'tel2', label: 'Téléphone 2', sectionId: 'identification', type: 'phone', order: 8 },
  { id: 'origine', label: 'Origine (wilaya)', sectionId: 'identification', type: 'enum', options: WILAYAS, order: 9 },
  { id: 'adresse', label: 'Adresse (wilaya de résidence)', sectionId: 'identification', type: 'enum', options: WILAYAS, order: 10 },
  { id: 'situation_familiale', label: 'Situation familiale', sectionId: 'identification', type: 'enum',
    options: opt('Marié(e)', 'Célibataire', 'Divorcé(e)', 'Veuf(ve)', 'Non précisé'), order: 11 },

  // ─────────── Antécédents ───────────
  { id: 'atcd_gyneco', label: 'ATCD gynécologiques', sectionId: 'atcd', type: 'multi',
    options: opt('Normoréglée', 'Aménorrhée', 'Ménopausée', 'Hystérectomisée', 'Ligature de trompes', 'Non précisé'), order: 1,
    visibleIf: { fieldId: 'sexe', equals: 'F' } },
  { id: 'atcd_perso_non_neo', label: 'ATCD personnels non néoplasiques', sectionId: 'atcd', type: 'multi',
    options: opt('Sans ATCD', 'HTA', 'Diabète', 'Allergie', 'Asthme bronchique', 'Cardiopathie', 'Neuropathie', 'Autres', 'Non précisé'), order: 2 },
  { id: 'atcd_perso_neo', label: 'ATCD personnels néoplasiques', sectionId: 'atcd', type: 'multi',
    options: opt('Sans ATCD', 'Néoplasie du sein', 'Néoplasie du côlon', 'Néoplasie du poumon', 'Néoplasie gynécologique', 'Lymphome', 'Néoplasie de la prostate', 'Néoplasie de l\'estomac', 'Autres', 'Non précisé'), order: 3 },
  { id: 'atcd_fam_endo', label: 'ATCD familiaux endocriniens', sectionId: 'atcd', type: 'multi',
    options: opt('Sans ATCD', 'Diabète', 'Pathologie thyroïdienne', 'Autres endocrinopathies', 'Non précisé'), order: 4 },
  { id: 'atcd_fam_cdt', label: 'ATCD familiaux CDT', sectionId: 'atcd', type: 'enum', options: YNNP, order: 5 },
  { id: 'atcd_fam_cdt_nb', label: 'Si oui : combien de CDT dans la famille', sectionId: 'atcd', type: 'number', min: 0, order: 6,
    visibleIf: { fieldId: 'atcd_fam_cdt', equals: 'Oui' } },

  // ─────────── Diagnostic CDT ───────────
  { id: 'cdd_cdt', label: 'Circonstances de découverte du CDT', sectionId: 'diagnostic_cdt', type: 'multi',
    options: opt('Nodule thyroïdien', 'GMN', 'Adénopathie', 'Dysthyroïdie', 'Fortuite', 'Métastase révélatrice', 'Bilan d\'extension', 'Non précisées'), order: 1 },
  { id: 'date_dgc_cdt', label: 'Date du diagnostic CDT', sectionId: 'diagnostic_cdt', type: 'date', order: 2 },
  { id: 'specialite_chir', label: 'Spécialité chirurgicale', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Chirurgie générale', 'ORL', 'Chirurgie thoracique', 'Autres'), order: 3 },
  { id: 'lieu_chir', label: 'Lieu de la chirurgie', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Secteur privé', 'CHU', 'EHS', 'EPH', 'EPSP'), order: 4 },
  { id: 'type_chir', label: 'Type de chirurgie', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Thyroïdectomie totale en un seul temps', 'Thyroïdectomie totale en deux temps', 'Thyroïdectomie subtotale', 'Thyroïdectomie partielle', 'Totalisation (après ancienne chirurgie)'), order: 5 },
  { id: 'curage_gg', label: 'Curage ganglionnaire', sectionId: 'diagnostic_cdt', type: 'enum', options: YNNP, order: 6 },
  { id: 'cg_temps', label: 'Si oui : en quel temps', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('en un seul temps', 'au premier temps', 'au deuxième temps', 'aux deux temps'), order: 7,
    visibleIf: { fieldId: 'curage_gg', equals: 'Oui' } },
  { id: 'cg_type', label: 'Si oui : type', sectionId: 'diagnostic_cdt', type: 'multi',
    options: opt('Central', 'Latéral unilatéral', 'Latéral bilatéral', 'Central et latéral unilatéral', 'Central et latéral bilatéral'), order: 8,
    visibleIf: { fieldId: 'curage_gg', equals: 'Oui' } },

  // ─────────── Histologie ───────────
  { id: 'type_histo', label: 'Type histologique', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Papillaire', 'Vésiculaire', 'Oncocytaire', 'Peu différencié', 'NIFTP', 'Non documenté'), order: 9 },
  { id: 'variante', label: 'Variante', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Classique', 'Vésiculaire', 'à cellules hautes', 'à cellules cylindriques', 'Sclérosant diffus', 'Oncocytaire', 'Cribriforme', 'Hobnail (Clou de tapissier)', 'Warthin Like', 'à invasion minime', 'Macro-invasif', 'à cellules claires', 'Pur', 'Insulaire', 'Trabéculaire', 'Solide', 'Trabéculo-solide', 'Autres'), order: 10 },
  { id: 'taille_t_cm', label: 'Taille T (plus grand) en cm', sectionId: 'diagnostic_cdt', type: 'number', min: 0, max: 30, order: 11 },
  { id: 'nombre_t', label: 'Nombre de tumeurs (T)', sectionId: 'diagnostic_cdt', type: 'number', min: 0, max: 50, order: 12 },
  { id: 'atteinte_lobaire', label: 'Atteinte lobaire', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Unilatéral', 'Bilatéral', 'Isthmique', 'Lobo-isthmique', 'Non précisée'), order: 13 },
  { id: 'effraction_capsulaire', label: 'Effraction capsulaire', sectionId: 'diagnostic_cdt', type: 'enum', options: YNNP, order: 14 },
  { id: 'atteinte_tissus', label: 'Atteinte des tissus avoisinants', sectionId: 'diagnostic_cdt', type: 'enum', options: YNNP, order: 15 },
  { id: 'emboles_vasc', label: 'Emboles vasculaires', sectionId: 'diagnostic_cdt', type: 'enum', options: YNNP, order: 16 },
  { id: 'emboles_nb', label: 'Si oui : nombre', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('≤ 4', '> 4', 'Non précisé'), order: 17,
    visibleIf: { fieldId: 'emboles_vasc', equals: 'Oui' } },
  { id: 'gg_reseques', label: 'Nombre de ganglions réséqués', sectionId: 'diagnostic_cdt', type: 'number', min: 0, order: 18 },
  { id: 'gg_atteints', label: 'Nombre de ganglions atteints', sectionId: 'diagnostic_cdt', type: 'number', min: 0, order: 19 },
  { id: 'ihc', label: 'Immunohistochimie (IHC)', sectionId: 'diagnostic_cdt', type: 'enum', options: opt('Oui', 'Non', 'Non documentée'), order: 20 },

  // ─────────── TNM ───────────
  { id: 'tnm_version', label: 'Version TNM', sectionId: 'diagnostic_cdt', type: 'enum', options: opt('2009', '2017'), order: 21 },
  { id: 'tnm_t', label: 'TNM initial — T', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Tx', 'T0', 'T1', 'T1a', 'T1b', 'T2', 'T3', 'T3a', 'T3b', 'T4', 'T4a', 'T4b'), order: 22 },
  { id: 'tnm_n', label: 'TNM initial — N', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Nx', 'N0', 'N1a', 'N1b'), order: 23 },
  { id: 'tnm_m', label: 'TNM initial — M', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('Mx', 'M0', 'M1'), order: 24 },
  { id: 'ajcc_version', label: 'Version AJCC', sectionId: 'diagnostic_cdt', type: 'enum', options: opt('2010', '2018'), order: 25 },
  { id: 'ajcc_initial', label: 'AJCC initial', sectionId: 'diagnostic_cdt', type: 'enum',
    options: opt('I', 'II', 'III', 'IVA', 'IVB', 'IVC'), order: 26 },

  // ─────────── Métastases (M1) ───────────
  { id: 'cdd_m1', label: 'Circonstances de découverte de M1', sectionId: 'metastases', type: 'multi',
    options: opt('Pas de métastases connues avant I1', 'Dyspnée', 'Hémoptysie', 'Dysphagie', 'Tuméfaction osseuse', 'Douleurs osseuses', 'Fracture', 'Compression médullaire', 'Hypercalcémie', 'Fortuite', 'Bilan d\'extension', 'Non précisées'), order: 1 },
  { id: 'date_dgc_m1', label: 'Date du diagnostic M1', sectionId: 'metastases', type: 'date', order: 2 },
  { id: 'm1_osseuse', label: 'M1 osseuse', sectionId: 'metastases', type: 'enum', options: YNNP, order: 3 },
  { id: 'm1_nb', label: 'Si oui : nombre', sectionId: 'metastases', type: 'number', min: 0, max: 100, order: 4,
    visibleIf: { fieldId: 'm1_osseuse', equals: 'Oui' } },
  { id: 'm1_rachis', label: 'Rachis', sectionId: 'metastases', type: 'enum', options: opt('Oui', 'Non'), order: 5,
    visibleIf: { fieldId: 'm1_osseuse', equals: 'Oui' } },
  { id: 'm1_pelvis', label: 'Pelvis', sectionId: 'metastases', type: 'enum', options: opt('Oui', 'Non'), order: 6,
    visibleIf: { fieldId: 'm1_osseuse', equals: 'Oui' } },
  { id: 'm1_thorax', label: 'Thorax', sectionId: 'metastases', type: 'enum', options: opt('Oui', 'Non'), order: 7,
    visibleIf: { fieldId: 'm1_osseuse', equals: 'Oui' } },
  { id: 'm1_crane', label: 'Crâne', sectionId: 'metastases', type: 'enum', options: opt('Oui', 'Non'), order: 8,
    visibleIf: { fieldId: 'm1_osseuse', equals: 'Oui' } },
  { id: 'm1_membres', label: 'Membres', sectionId: 'metastases', type: 'enum', options: opt('Oui', 'Non'), order: 9,
    visibleIf: { fieldId: 'm1_osseuse', equals: 'Oui' } },
  { id: 'biopsie_osseuse', label: 'Biopsie osseuse', sectionId: 'metastases', type: 'enum', options: YNNP, order: 10 },
  { id: 'chir_osseuse', label: 'Chirurgie osseuse', sectionId: 'metastases', type: 'enum', options: YNNP, order: 11 },
  { id: 'autres_metastases', label: 'Autres métastases', sectionId: 'metastases', type: 'multi',
    options: opt('Non documenté', 'Non', 'Ganglionnaires', 'Pulmonaires', 'Cérébrales', 'Hépatiques', 'Cutanéo-musculaires', 'Autres'), order: 12 },
  { id: 'age_dgc_cdt', label: 'Âge au diagnostic CDT', sectionId: 'metastases', type: 'number', min: 0, max: 120, order: 13 },
  { id: 'age_dgc_m1', label: 'Âge au diagnostic M1', sectionId: 'metastases', type: 'number', min: 0, max: 120, order: 14 },
  { id: 'delai_m1_t_mois', label: 'Délai Dg M1 / Dgc T (mois)', sectionId: 'metastases', type: 'number', min: 0, max: 600, order: 15 },

  // ─────────── Bilan d'extension ───────────
  { id: 'echo_cervicale', label: 'Échographie cervicale', sectionId: 'bilan_extension', type: 'enum', options: opt('Faite', 'Non faite'), order: 1 },
  { id: 'eu_tirads', label: 'Classification EU-TIRADS', sectionId: 'bilan_extension', type: 'enum', options: opt('1', '2', '3', '4', '5'), order: 2,
    visibleIf: { fieldId: 'echo_cervicale', equals: 'Faite' } },
  { id: 'cytologie', label: 'Cytologie thyroïdienne', sectionId: 'bilan_extension', type: 'enum', options: opt('Oui', 'Non', 'Non documentée'), order: 3 },
  { id: 'bethesda', label: 'Classification Bethesda', sectionId: 'bilan_extension', type: 'enum', options: opt('I', 'II', 'III', 'IV', 'V', 'VI'), order: 4,
    visibleIf: { fieldId: 'cytologie', equals: 'Oui' } },
  { id: 'tdm_initiale', label: 'TDM thoracique / TAP', sectionId: 'bilan_extension', type: 'enum', options: opt('Faite', 'Non faite'), order: 5 },
  { id: 'irm_initiale', label: 'IRM cérébro-médullaire', sectionId: 'bilan_extension', type: 'enum', options: opt('Faite', 'Non faite'), order: 6 },
  { id: 'so_initiale', label: 'Scintigraphie osseuse', sectionId: 'bilan_extension', type: 'enum', options: opt('Faite', 'Non faite'), order: 7 },
  { id: 'tep_fdg', label: 'TEP-FDG', sectionId: 'bilan_extension', type: 'enum', options: opt('Faite', 'Non faite'), order: 8 },
  { id: 'tsh_externe', label: 'TSHus (µUI/ml) — externe', sectionId: 'bilan_extension', type: 'number', min: 0, order: 9 },
  { id: 'ft4_externe', label: 'FT4 (pmol/l) — externe', sectionId: 'bilan_extension', type: 'number', min: 0, order: 10 },
  { id: 'tg_externe', label: 'Tg (ng/ml) — externe', sectionId: 'bilan_extension', type: 'number', min: 0, order: 11 },
  { id: 'atg_externe', label: 'Ac anti-Tg (UI/ml)', sectionId: 'bilan_extension', type: 'number', min: 0, order: 12 },
  { id: 'tct', label: 'TCT (pg/ml)', sectionId: 'bilan_extension', type: 'number', min: 0, order: 13 },

  // ─────────── Préparation I1 ───────────
  { id: 'date_ouverture', label: 'Date d\'ouverture du dossier', sectionId: 'preparation_i1', type: 'date', order: 1 },
  { id: 'etat_general', label: 'État général', sectionId: 'preparation_i1', type: 'enum', options: opt('Bon', 'Moyen', 'Mauvais'), order: 2 },
  { id: 'autonomie', label: 'Autonomie', sectionId: 'preparation_i1', type: 'enum', options: opt('Oui', 'Non'), order: 3 },
  { id: 'deambulation', label: 'Déambulation', sectionId: 'preparation_i1', type: 'enum',
    options: opt('Conservée', 'Ralentie', 'avec canne', 'avec béquilles', 'sur fauteuil roulant', 'Patient(e) alité(e)'), order: 4 },
  { id: 'karnofsky', label: 'Score de Karnofsky', sectionId: 'preparation_i1', type: 'enum',
    options: opt('100-90', '80-70', '60-50', '40-30', '≤ 20'), order: 5 },
  { id: 'douleur', label: 'Douleur', sectionId: 'preparation_i1', type: 'enum', options: opt('Oui', 'Non'), order: 6 },
  { id: 'douleur_eva', label: 'EVA (0-10)', sectionId: 'preparation_i1', type: 'number', min: 0, max: 10, order: 7,
    visibleIf: { fieldId: 'douleur', equals: 'Oui' } },
  { id: 'trouble_neuro', label: 'Trouble neurologique', sectionId: 'preparation_i1', type: 'multi',
    options: opt('Absent', 'Paresthésie-Hypoesthésie', 'Douleur radiculaire', 'Faiblesse musculaire', 'Parésie-Paralysie', 'Amyotrophie', 'Incontinence urinaire'), order: 8 },
  { id: 'sous_l_thyroxine_pre', label: 'Sous L-Thyroxine', sectionId: 'preparation_i1', type: 'enum', options: opt('Oui', 'Non'), order: 9 },
  { id: 'freinage_pre', label: 'Degré de freinage', sectionId: 'preparation_i1', type: 'enum',
    options: opt('Bien freiné', 'Mal freiné', 'en hypothyroïdie', 'Non précisé'), order: 10,
    visibleIf: { fieldId: 'sous_l_thyroxine_pre', equals: 'Oui' } },
  { id: 'ec_pre_i1', label: 'EC pré-I1', sectionId: 'preparation_i1', type: 'multi',
    options: opt('Non faite', 'RAS', 'Reliquat thyroïdien', 'Nodule thyroïdien', 'Lobe restant', 'Adénopathies', 'Extension extra-thyroïdienne'), order: 11 },

  // ─────────── Cures Iode 131 (générique, le user duplique pour I1...I6) ───────────
  { id: 'i1_date', label: 'Date I1', sectionId: 'cures_iode', type: 'date', order: 1 },
  { id: 'i1_activite', label: 'Activité I1 (mCi)', sectionId: 'cures_iode', type: 'number', min: 0, max: 1000, order: 2 },
  { id: 'i1_stimulation', label: 'Modalités de stimulation I1', sectionId: 'cures_iode', type: 'enum',
    options: opt('Endogène', 'Exogène', 'Mixte'), order: 3 },
  { id: 'i1_sevrage', label: 'Durée du sevrage L-Thyroxine I1', sectionId: 'cures_iode', type: 'enum',
    options: opt('1 semaine', '2 semaines', '3 semaines', '4 semaines', '5 semaines', '6 semaines', '> 6 semaines'), order: 4,
    visibleIf: { fieldId: 'i1_stimulation', equals: 'Endogène' } },
  { id: 'i1_tolerance', label: 'Tolérance clinique I1', sectionId: 'cures_iode', type: 'multi',
    options: opt('Asymptomatique', 'Œdème cervical', 'Nausées', 'Vomissements', 'Céphalées', 'Sialadénite', 'Gastralgies', 'Douleurs osseuses', 'Dyspnée', 'Autres', 'Non précisé'), order: 5 },
  { id: 'i1_bpt', label: 'Réalisation de BPT 1', sectionId: 'cures_iode', type: 'enum', options: opt('Oui', 'Non'), order: 6 },
  { id: 'i1_eval', label: 'Évaluation I1', sectionId: 'cures_iode', type: 'multi',
    options: opt('RC clinique', 'RP clinique', 'RS clinique', 'PD clinique',
      'RC biologique', 'RP biologique', 'RS biologique', 'PD biologique',
      'RC radiologique', 'RP radiologique', 'RS radiologique', 'PD radiologique'), order: 7 },

  // ─────────── Suivi global ───────────
  { id: 'suivi_duree_mois', label: 'Durée totale de suivi en IRA (mois)', sectionId: 'suivi_global', type: 'number', min: 0, max: 600, order: 1 },
  { id: 'eval_globale', label: 'Évaluation globale', sectionId: 'suivi_global', type: 'enum',
    options: opt('RC', 'RP', 'RS', 'PD'), order: 2 },
  { id: 'statut_clinique', label: 'Statut clinique global', sectionId: 'suivi_global', type: 'enum',
    options: opt('RC clinique', 'RP clinique', 'RS clinique', 'PD clinique'), order: 3 },
  { id: 'statut_bio', label: 'Statut biologique global', sectionId: 'suivi_global', type: 'enum',
    options: opt('RC biologique', 'RP biologique', 'RS biologique', 'PD biologique'), order: 4 },
  { id: 'statut_iso', label: 'Statut isotopique global', sectionId: 'suivi_global', type: 'enum',
    options: opt('RC', 'RP', 'RS', 'PD'), order: 5 },
  { id: 'statut_radio', label: 'Statut radiologique global', sectionId: 'suivi_global', type: 'enum',
    options: opt('RC radiologique', 'RP radiologique', 'RS radiologique', 'PD radiologique'), order: 6 },

  // ─────────── Devenir ───────────
  { id: 'antalgiques', label: 'Antalgiques', sectionId: 'devenir', type: 'enum',
    options: opt('Non', 'C1', 'C2', 'C3'), order: 1 },
  { id: 'rte', label: 'RTE (Radiothérapie externe)', sectionId: 'devenir', type: 'enum', options: opt('Oui', 'Non'), order: 2 },
  { id: 'bp_denosumab', label: 'Bisphosphonates / Dénosumab', sectionId: 'devenir', type: 'enum', options: opt('Oui', 'Non'), order: 3 },
  { id: 'chir_mo', label: 'Chirurgie MO', sectionId: 'devenir', type: 'enum', options: opt('Oui', 'Non'), order: 4 },
  { id: 'tki', label: 'TKI', sectionId: 'devenir', type: 'enum',
    options: opt('Non', 'Sorafénib', 'Lenvatinib', 'Cabozantinib'), order: 5 },
  { id: 'date_envoi_onco', label: 'Date d\'envoi en oncologie', sectionId: 'devenir', type: 'date', order: 6 },
  { id: 'deces', label: 'Décès', sectionId: 'devenir', type: 'enum', options: opt('Oui', 'Non'), order: 7 },
  { id: 'date_deces', label: 'Date de décès', sectionId: 'devenir', type: 'date', order: 8,
    visibleIf: { fieldId: 'deces', equals: 'Oui' } },
];

export function buildInitialSchema(): FormSchema {
  return {
    version: 1,
    updatedAt: Date.now(),
    sections: SECTIONS,
    fields: FIELDS,
  };
}
